dist: trusty
sudo: false

language: cpp

before_install:
  - git submodule init
  - git submodule update

script:
  - cmake -H. -Bbuild
  - cmake --build build && ./build/test/base/libjigle_base_test && ./build/test/xmllite/libjigle_xmllite_test

notifications:
  email: false
