dist: trusty
sudo: false

language: cpp

before_install:
  - git submodule init
  - git submodule update

script:
  - cmake -H. -Bbuild
  - cmake --build build && ./build/test/libjigle_tst

notifications:
  email: false
